[package]
name = "pwzip-creator"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4"
actix-multipart = "0.7.2"
futures = "0.3"
tempfile = "3"
serde = { version = "1.0", features = ["derive"] }